/* sprites.h - generated by tools/sprite2asm.py - do not edit. */
#ifndef SPRITES_H
#define SPRITES_H
#include <stdint.h>

extern const uint8_t SprSquidA[26];   /* 8x6 */
extern const uint8_t SprSquidB[26];   /* 8x6 */
extern const uint8_t SprCrabA[26];   /* 8x6 */
extern const uint8_t SprCrabB[26];   /* 8x6 */
extern const uint8_t SprOctoA[26];   /* 8x6 */
extern const uint8_t SprOctoB[26];   /* 8x6 */
extern const uint8_t SprPlayer[32];   /* 9x6 */
extern const uint8_t SprPBoomA[32];   /* 9x6 */
extern const uint8_t SprPBoomB[32];   /* 9x6 */
extern const uint8_t SprUfo[50];   /* 16x6 */
extern const uint8_t SprBoom[30];   /* 8x7 */
extern const uint8_t SprPShot[7];   /* 1x5 */
extern const uint8_t SprEShotA[12];   /* 3x5 */
extern const uint8_t SprEShotB[12];   /* 3x5 */
extern const uint8_t SprCapsule[30];   /* 7x7 */
extern const uint8_t SprSpark[8];   /* 3x3 */
extern const uint8_t SprMiniShip[11];   /* 5x3 */

#endif
